flags: {}
nix:
  packages:
  - zlib
  - haskellPackages.gtk2hs-buildtools
  - haskellPackages.happy
  - haskellPackages.alex
  - cabal-install
  - pkgconfig
  - webkitgtk2
  - glib
  - cairo
  - pango
  enable: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- webkit-0.14.2.1
resolver: lts-7.14
